project:
  type: website
  render:
    - "*.ipynb"

format:
  html:
    toc: true
    css: styles.css
    code-block-bg: true
    code-overflow: wrap
    code-line-numbers: false
    monofont: D2Coding
    language:
      crossref-tbl-title: "표"
    mermaid:
      theme: neutral

bibliography: references.bib
reference-location: margin

website:
  title: "Git Book"
  sidebar:
    style: "docked"
    search: true
    contents:
      - "index.ipynb"
      - "command.ipynb"
      - "repo.ipynb"
      - "basic.ipynb"
      - "object.ipynb"
      - "commit.ipynb"
      - "branch.ipynb"
      - "merge.ipynb"
      - "reference.ipynb"
